<a href="https://colab.research.google.com/github/smchakma/ResearchWithSkillMoprh/blob/main/4th_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

file_path = '/content/drive/MyDrive/Datasets/healthcare_cybersecurity_10k.csv'

df = pd.read_csv(file_path)
print('loaded: ', df.shape)

loaded:  (1515, 11)

In [3]:
df.head()

,CVE_ID,Keyword,Published,Last_Modified,Status,Description,Severity,CVSS_Score,Attack_Vector,Weakness,Reference
0,CVE-2011-3386,medical device,2011-09-02,2025-04-11,Deferred,Unspecified vulnerability in Medtronic Paradig...,MEDIUM,4.0,NETWORK,NVD-CWE-noinfo,http://sixuntilme.com/blog2/2011/08/hacked_jay...
1,CVE-2017-12718,medical device,2018-02-15,2024-11-21,Modified,A Classic Buffer Overflow issue was discovered...,MEDIUM,6.8,NETWORK,CWE-120,http://www.securityfocus.com/bid/100665
2,CVE-2017-14002,medical device,2018-03-20,2024-11-21,Modified,GE Infinia/Infinia with Hawkeye 4 medical imag...,HIGH,10.0,NETWORK,CWE-287,http://www.securityfocus.com/bid/103405
3,CVE-2017-14006,medical device,2018-03-20,2024-11-21,Modified,"GE Xeleris versions 1.0,1.1,2.1,3.0,3.1, medic...",HIGH,7.5,NETWORK,CWE-287,https://ics-cert.us-cert.gov/advisories/ICSMA-...
4,CVE-2019-5024,medical device,2019-04-11,2024-11-21,Modified,A restricted environment escape vulnerability ...,HIGH,7.6,PHYSICAL,CWE-693,https://talosintelligence.com/vulnerability_re...

In [4]:
df.describe()

        CVSS_Score
count  1497.000000
mean      6.554108
std       1.956064
min       1.900000
25%       5.400000
50%       6.500000
75%       7.600000
max      10.000000

In [5]:
df.tail()

,CVE_ID,Keyword,Published,Last_Modified,Status,Description,Severity,CVSS_Score,Attack_Vector,Weakness,Reference
1510,CVE-2023-32781,HL7,2023-08-09,2024-11-21,Modified,A command injection vulnerability was identifi...,HIGH,7.2,NETWORK,CWE-77,http://packetstormsecurity.com/files/176677/PR...
1511,CVE-2023-28465,HL7,2023-12-12,2025-05-27,Modified,The package-decompression feature in HL7 (Heal...,HIGH,7.5,NETWORK,CWE-22,https://github.com/advisories/GHSA-9654-pr4f-gh6m
1512,CVE-2024-52807,HL7,2025-01-24,2026-04-15,Deferred,The HL7 FHIR IG publisher is a tool to take a ...,HIGH,8.6,NETWORK,CWE-611,https://github.com/HL7/fhir-ig-publisher/commi...
1513,CVE-2025-24363,HL7,2025-01-24,2026-04-15,Deferred,The HL7 FHIR IG publisher is a tool to take a ...,MEDIUM,4.2,LOCAL,CWE-200,https://github.com/HL7/fhir-ig-publisher/commi...
1514,CVE-2025-53948,HL7,2025-08-18,2025-10-17,Analyzed,The Sante PACS Server allows a remote attacker...,HIGH,7.5,NETWORK,CWE-415,https://www.cisa.gov/news-events/ics-medical-a...

In [7]:
print('Missing per column: \n', df.isnull().sum())
print('\nClass Balance: \n', df['Severity'].value_counts())

Missing per column:
 CVE_ID            0
Keyword           0
Published         0
Last_Modified     0
Status            0
Description       0
Severity         18
CVSS_Score       18
Attack_Vector    18
Weakness          1
Reference         0
dtype: int64

Class Balance:
 Severity
MEDIUM      720
HIGH        492
CRITICAL    151
LOW         134
Name: count, dtype: int64