<a href="https://colab.research.google.com/github/smchakma/ResearchWithSkillMoprh/blob/main/Matplotlib_and_seaborn_asg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##Matplotlib
###Bar chart of membership types

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
DATA_DIR = '/content/drive/MyDrive/Datasets/'
gym = pd.read_csv(f'{DATA_DIR}/gym_membership.csv')

print(f'gym: {gym.shape}')

gym: (1000, 17)

In [5]:
gym.head()

,id,gender,birthday,Age,abonoment_type,visit_per_week,days_per_week,attend_group_lesson,fav_group_lesson,avg_time_check_in,avg_time_check_out,avg_time_in_gym,drink_abo,fav_drink,personal_training,name_personal_trainer,uses_sauna
0,1,Female,4/18/1997,27,Premium,4,"Mon, Sat, Tue, Wed",True,"Kickboxen, BodyPump, Zumba",19:31:00,21:27:00,116,False,NaN,False,NaN,True
1,2,Female,9/18/1977,47,Standard,3,"Mon, Sat, Wed",False,NaN,19:31:00,20:19:00,48,False,NaN,True,Chantal,False
2,3,Male,3/30/1983,41,Premium,1,Sat,True,XCore,8:29:00,10:32:00,123,True,"berry_boost, lemon",True,Mike,False
3,4,Male,4/12/1980,44,Premium,3,"Sat, Tue, Wed",False,NaN,9:54:00,11:33:00,99,True,passion_fruit,True,Mike,True
4,5,Male,9/10/1980,44,Standard,2,"Thu, Wed",True,"Running, Yoga, Zumba",8:29:00,9:19:00,50,False,NaN,True,Mike,False

In [6]:
gym.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     1000 non-null   int64
 1   gender                 1000 non-null   object
 2   birthday               1000 non-null   object
 3   Age                    1000 non-null   int64
 4   abonoment_type         1000 non-null   object
 5   visit_per_week         1000 non-null   int64
 6   days_per_week          1000 non-null   object
 7   attend_group_lesson    1000 non-null   bool
 8   fav_group_lesson       503 non-null    object
 9   avg_time_check_in      1000 non-null   object
 10  avg_time_check_out     1000 non-null   object
 11  avg_time_in_gym        1000 non-null   int64
 12  drink_abo              1000 non-null   bool
 13  fav_drink              496 non-null    object
 14  personal_training      1000 non-null   bool
 15  name_personal_trainer  518 non-null    object
 16  uses_sauna             1000 non-null   bool
dtypes: bool(4), int64(4), object(9)
memory usage: 105.6+ KB

In [7]:
gym.describe()

                id          Age  visit_per_week  avg_time_in_gym
count  1000.000000  1000.000000     1000.000000      1000.000000
mean    500.500000    30.604000        2.682000       105.260000
std     288.819436    10.817958        1.241941        43.557177
min       1.000000    12.000000        1.000000        30.000000
25%     250.750000    21.000000        2.000000        67.000000
50%     500.500000    30.000000        3.000000       104.000000
75%     750.250000    40.000000        3.000000       143.000000
max    1000.000000    49.000000        5.000000       180.000000